version: "3"

services:
  ssh-node:
    container_name: node1
    user: root
    restart: always
    image: 'registry.cn-hangzhou.aliyuncs.com/pendevs/jenkins:ssh-node-jdk'
    hostname: node1-container
    ports:
      - "61102:22"
    working_dir: /usr/src/app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/node1/:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
    #command: /usr/local/bin/gunicorn web.wsgi:application -w 2 -b :8077
    deploy:
      resources:
        limits:
          cpus: "2.00"
          memory: 2G
        reservations:
          memory: 500M


networks:
  customize_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.37.0/24